apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/backend
- ../../base/frontend

commonLabels:
  env: prod

images:
- name: kea-004-onlog-blog-server
  newTag: v1
  