apiVersion: v1
kind: Service
metadata:
  name: onlog-front-service
  namespace: onlog-frontend
spec:
  selector:
    app: onlog-front
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer