apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlog-blog-server-deployment
  labels:
    app: onlog-blog-server
    tier: backend

spec:
  replicas: 3
  selector:
    matchLabels:
      app: onlog-blog-server
      tier: backend

  template:
    metadata:
      labels:
        app: onlog-blog-server
        tier: backend
        common: onlog

    spec:
      containers:
      - name: blog-server
        image: 629515838455.dkr.ecr.us-east-1.amazonaws.com/kea-004-onlog-blog-server:52
        ports:
        - containerPort: 80