apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlog-front-deployment
  namespace: onlog-frontend
  labels:
    app: onlog-front
    tier: frontend
spec:
  replicas: 3
  revisionHistoryLimit: 6
  selector:
    matchLabels:
      app: onlog-front
      tier: frontend
  template:
    metadata:
      labels:
        app: onlog-front
        tier: frontend
    spec:
      containers:
      - name: onlog-front
        image: 629515838455.dkr.ecr.us-east-1.amazonaws.com/kea-004-onlog-front:24
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf