apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlog-profanity-detection-server-deployment
  labels:
    app: onlog-profanity-detection-server
    tier: backend

spec:
  replicas: 3
  selector:
    matchLabels:
      app: onlog-profanity-detection-server
      tier: backend

  template:
    metadata:
      labels:
        app: onlog-profanity-detection-server
        tier: backend
        
    spec:
      containers:
      - name: profanity-detection-server
        image: kidevelop/appropriate-filetering
        ports:
        - containerPort: 8090

---
apiVersion: v1
kind: Service
metadata:
  name: onlog-profanity-detection-server-service

spec:
  selector:
    app: onlog-profanity-detection-server
    tier: backend

  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090

  type: ClusterIP
